const fs = require("fs");

// Step 1: Read students.txt
fs.readFile("student.txt", "utf-8", (err, data) => {
  if (err) return console.log("Error reading file:", err.message);

  console.log("=== Student List ===");
  console.log(data);

  const students = data.trim().split("\n");
  const count = students.length;

  // Step 2: Write report.txt (inside step 1's callback)
  const reportContent = `GeoAttend Report\n================\nTotal students read: ${count}\n`;

  fs.writeFile("report.txt", reportContent, (err) => {
    if (err) return console.log("Error writing file:", err.message);

    console.log("✅ report.txt created!");

    // Step 3: Append to report.txt (inside step 2's callback)
    fs.appendFile("report.txt", "Generated by: Yaw\n", (err) => {
      if (err) return console.log("Error appending:", err.message);

      console.log("✅ Entry appended!");

      // Step 4: Read report.txt back (inside step 3's callback)
      fs.readFile("report.txt", "utf-8", (err, finalData) => {
        if (err) return console.log("Error reading report:", err.message);

        console.log("\n=== Final Report ===");
        console.log(finalData);
      });
    });
  });
});
